// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: paxos_service.proto
// Protobuf Java Version: 4.28.2

package br.ufrn.imd.pd.common.proto;

public interface GenericResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.ufrn.imd.pd.GenericResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  int getHeadersCount();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  boolean containsHeaders(
      java.lang.String key);
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaders();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeadersMap();
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  /* nullable */
java.lang.String getHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; headers = 3;</code>
   */
  java.lang.String getHeadersOrThrow(
      java.lang.String key);

  /**
   * <code>string body = 4;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
