// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: paxos_service.proto
// Protobuf Java Version: 4.28.2

package br.ufrn.imd.pd.common.proto;

public final class PaxosService {
  private PaxosService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PaxosService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufrn_imd_pd_GenericRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufrn_imd_pd_GenericRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufrn_imd_pd_GenericRequest_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufrn_imd_pd_GenericRequest_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufrn_imd_pd_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufrn_imd_pd_GenericResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufrn_imd_pd_GenericResponse_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_ufrn_imd_pd_GenericResponse_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023paxos_service.proto\022\016br.ufrn.imd.pd\"\252\001" +
      "\n\016GenericRequest\022\016\n\006method\030\001 \001(\t\022\014\n\004path" +
      "\030\002 \001(\t\022<\n\007headers\030\003 \003(\0132+.br.ufrn.imd.pd" +
      ".GenericRequest.HeadersEntry\022\014\n\004body\030\004 \001" +
      "(\t\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"\263\001\n\017GenericResponse\022\023\n\013status" +
      "_code\030\001 \001(\005\022\016\n\006method\030\002 \001(\t\022=\n\007headers\030\003" +
      " \003(\0132,.br.ufrn.imd.pd.GenericResponse.He" +
      "adersEntry\022\014\n\004body\030\004 \001(\t\032.\n\014HeadersEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012_\n\020Paxo" +
      "sNodeService\022K\n\010Exchange\022\036.br.ufrn.imd.p" +
      "d.GenericRequest\032\037.br.ufrn.imd.pd.Generi" +
      "cResponseB\037\n\033br.ufrn.imd.pd.common.proto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_br_ufrn_imd_pd_GenericRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_ufrn_imd_pd_GenericRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufrn_imd_pd_GenericRequest_descriptor,
        new java.lang.String[] { "Method", "Path", "Headers", "Body", });
    internal_static_br_ufrn_imd_pd_GenericRequest_HeadersEntry_descriptor =
      internal_static_br_ufrn_imd_pd_GenericRequest_descriptor.getNestedTypes().get(0);
    internal_static_br_ufrn_imd_pd_GenericRequest_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufrn_imd_pd_GenericRequest_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_br_ufrn_imd_pd_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_br_ufrn_imd_pd_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufrn_imd_pd_GenericResponse_descriptor,
        new java.lang.String[] { "StatusCode", "Method", "Headers", "Body", });
    internal_static_br_ufrn_imd_pd_GenericResponse_HeadersEntry_descriptor =
      internal_static_br_ufrn_imd_pd_GenericResponse_descriptor.getNestedTypes().get(0);
    internal_static_br_ufrn_imd_pd_GenericResponse_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_ufrn_imd_pd_GenericResponse_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
